// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_setSeed 22
#define SYS_getRandomNumber 23
#define SYS_process_information 24
#define SYS_sort_numbers 25

#define SYS_set_scheduling_info 26
#define SYS_change_queue 27
#define SYS_print_scheduling_info 28
#define SYS_getcount 29
#define SYS_getcpucount 30
#define SYS_produce 31
#define SYS_consume 32
#define SYS_rw_acquire_read 33
#define SYS_rw_release_read 34
#define SYS_rw_acquire_write 35
#define SYS_rw_release_write 36
#define SYS_ticket_acquire 37
#define SYS_ticket_release 38
#define SYS_ticket_turn 39

#define SYS_waitstats 40
#define SYS_try_produce 41
#define SYS_try_consume 42
#define SYS_consume_value 43
#define SYS_getcountmode 44
